apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-games
resources:
  - simple-frontend-deploy.yaml
  - simple-frontend-service.yaml
  - api-genre-deploy.yaml
  - api-genre-service.yaml
  - api-region-deploy.yaml
  - api-region-service.yaml
  - game-store-db-deploy.yaml
  - game-store-db-service.yaml
  - ingress-genre-region.yaml
  - namespace.yaml
configMapGenerator:
  - name: mysql-dump-config
    files:
    - videogames-db.sql
  - name: index-html
    files: 
    - index.html
secretGenerator:
- name: mysql-cred
  envs:
  - database-cred